src/guide/api/types.rst

Depends on https://gitlab.flyingcircus.io/flyingcircus/fc.directory/merge_requests/1
bugs id: #108570

documentation for maintenance api

---

src/reference/security/backup.rst

document verification of backups

---

src/reference/security/data-protection.rst

bugs id: #129339
@ctheune could you review the wording, please?

clarify the wording around keeping passwords secure

---

src/guide/vms/index.rst

related to TSK-0095
See also permission inconsitency in PL-129494

discourage rebooting on commandline due to integration with monitoring

---

src/reference/security/data-protection.rst

Review VM related security documentation

---

bootstrap.sh
buildout.cfg
default.nix
src/conf.py
versions.cfg

* Support Python 3.9, 3.8
* Add buildout version updater so updating versions becomes easy

Generally update versions

---

src/index.rst
src/platform/21.05/fc-21.05-dev.rst
src/platform/21.05/fc-21.05-production.rst
src/platform/21.05/fc-21.05-staging.rst
src/platform/21.05/index.rst

Enables 21.09 documentation to be displayed.

Add 21.05 documentation support

---

src/infrastructure/storage.md

Relocating from our wiki to make it available to our customers.

Document our Application Development Guidance WRT S3/bucket usage

---

src/reference/security/backup.md
src/reference/security/index.md

ISMS document review

---

src/reference/security/disaster-recovery.md
src/reference/security/network.md
src/reference/security/software-vulnerabilities.md
src/reference/users/index.md

Minor updates as noticed during the yearly review.

---

src/reference/security/administrators.md

This MR updates the list of our stand-by supporters for new Nils and Philipp
#FC-37707
#FC-37706

Add Nils and Philipp as new stand-by supporters

---

src/infrastructure/storage.md

Explain our strategie for the 3 disk types in VMs.

---

src/reference/security/policy.md

Update ISMS policy released on 2024-06-20

---

src/guide/deployment/index.md
src/guide/deployment/mongodb.md

Public to make sure hosted/guided customers benefit from this as well.

[FC-38101] guide: add mongodb instructions

---

changelog-release
changelog.d/scriv.ini
src/changes/2024/r031.md
src/changes/skel

[PL-133099](https://yt.flyingcircus.io/issue/PL-133099)

Use scriv for Changelog management

---

src/guide/api/types.md

Relates to https://gitlab.flyingcircus.io/flyingcircus/fc.directory/-/merge_requests/495

Document API maintenance functionality

---

src/reference/security/data-protection.md

Remove obsolete and wrong 2FA examples

---

src/guide/api/types.md
src/reference/security/backup.md

DIR-1195
see also https://gitlab.flyingcircus.io/flyingcircus/fc.directory/-/merge_requests/529

Documentation for API which allows updating the backy_schedule

---

src/infrastructure/networking/networking.md
src/locales/de/LC_MESSAGES/reference/security/data-protection.po
src/reference/security/backup.md
src/reference/security/data-protection.md
src/reference/security/disaster-recovery.md
src/reference/security/network.md

ISMS-147656
@ctheune please review english document. I mostly moved text around but there are also some new parts.

Update structure to fit BDSG

---

src/reference/security/disaster-recovery.md
src/reference/security/network.md
src/reference/security/software-vulnerabilities.md
src/reference/users/index.md

review (resulted in sub tickets) and update of isms controls
